import { cn } from '@/lib/utils'

import './globals.css'

import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ReactNode } from 'react'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Team Chat Application',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<ClerkProvider>
			<html lang="pt-BR">
				<body className={cn('antialiased', font.className)}>
					{children}
				</body>
			</html>
		</ClerkProvider>
	)
}
