import { cn } from '@/lib/utils'

import './globals.css'

import { ModalProvider } from '@/components/providers/modal-provider'
import { SocketProvider } from '@/components/providers/socket-provider'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ReactNode } from 'react'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Team Chat Application',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<ClerkProvider>
			<html lang="pt-BR" suppressHydrationWarning>
				<body
					className={cn(
						'bg-white antialiased dark:bg-[#313338]',
						font.className,
					)}
				>
					<ThemeProvider
						attribute="class"
						defaultTheme="dark"
						enableSystem={false}
						storageKey="discord-theme"
					>
						<SocketProvider>
							<ModalProvider />
							{children}
						</SocketProvider>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
